# Generated by Django 4.2.4 on 2023-09-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='status',
        ),
    ]
