# Generated by Django 4.2.4 on 2023-09-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_biblioteca_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='preço',
            field=models.FloatField(default=0),
        ),
    ]
