# Generated by Django 4.2.4 on 2023-08-31 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pronto', 'Pronto'), ('Em Andamento', 'Em Andamento'), ('Pendente', 'Pendente')], max_length=12)),
                ('pessoa', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='todo.pessoa')),
            ],
        ),
    ]
